apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.database }}"
        volumeMounts:
        - name: sql-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: sql-init
        configMap:
          name: init-sql-configmap